export const UPDATE_LOADING = "UPDATE_LOADING";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_LOGIN = "CREATE_LOGIN";
export const GET_ALL_CLINICS = "GET_ALL_CLINICS";
export const GET_ALL_CLINICS_TYPES = "GET_ALL_CLINICS_TYPES";
export const GET_CLINIC = "GET_CLINIC";
export const GET_DADOS_PROFILE = "GET_DADOS_PROFILE";
export const GET_ALL_DADOS_PROFILE = "GET_ALL_DADOS_PROFILE";
export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS";
export const LOGOUT = "LOGOUT";
export const RESET_STORE = "RESET_STORE";
export const GET_ALL_PROCEDURES = "GET_ALL_PROCEDURES";
export const GET_ALL_APPOINTMENTS_TYPE = "GET_ALL_APPOINTMENTS_TYPE";
export const SAVE_PHOTO_USER = "SAVE_PHOTO_USER";
export const SAVE_PROFILE_ID = "SAVE_PROFILE_ID";
export const GET_ALL_APPOINTMENTS_DENTIST = "GET_ALL_APPOINTMENTS_DENTIST";
export const GET_ALL_APPOINTMENTS_PACIENT = "GET_ALL_APPOINTMENTS_PACIENT";
export const GET_ALL_APPOINTMENTS_CLINIC = "GET_ALL_APPOINTMENTS_CLINIC";
export const GET_ALL_STATUS = "GET_ALL_STATUS";
export const GET_ADDRESS = "GET_ADDRESS";
export const GET_CITIES = "GET_CITIES";
export const GET_STATES = "GET_STATES";

const Constants = {
  UPDATE_LOADING,
  CREATE_ACCOUNT,
  GET_CITIES,
  GET_STATES,
  GET_ADDRESS,
  RESET_STORE,
  GET_ALL_STATUS,
  GET_ALL_APPOINTMENTS_DENTIST,
  CREATE_LOGIN,
  SAVE_PROFILE_ID,
  GET_ALL_CLINICS_TYPES,
  GET_ALL_CLINICS,
  GET_DADOS_PROFILE,
  GET_ALL_APPOINTMENTS_CLINIC,
  GET_CLINIC,
  GET_ALL_APPOINTMENTS_PACIENT,
  GET_ALL_DADOS_PROFILE,
  GET_ALL_PROCEDURES,
  GET_ALL_APPOINTMENTS_TYPE,
  GET_ALL_APPOINTMENTS,
  SAVE_PHOTO_USER,
  LOGOUT,
};

export default Constants;
