export const UPDATE_LOADING = "UPDATE_LOADING";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_LOGIN = "CREATE_LOGIN";
export const GET_ALL_CLINICS = "GET_ALL_CLINICS";
export const GET_DADOS_PROFILE = "GET_DADOS_PROFILE";
export const GET_ALL_DADOS_PROFILE = "GET_ALL_DADOS_PROFILE";
export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS";
export const LOGOUT = "LOGOUT";
export const GET_ALL_PROCEDURES = "GET_ALL_PROCEDURES";
export const GET_ALL_APPOINTMENTS_TYPE = "GET_ALL_APPOINTMENTS_TYPE";
export const SAVE_PHOTO_USER = "SAVE_PHOTO_USER";

const Constants = {
  UPDATE_LOADING,
  CREATE_ACCOUNT,
  CREATE_LOGIN,
  GET_ALL_CLINICS,
  GET_DADOS_PROFILE,
  GET_ALL_DADOS_PROFILE,
  GET_ALL_PROCEDURES,
  GET_ALL_APPOINTMENTS_TYPE,
  GET_ALL_APPOINTMENTS,
  SAVE_PHOTO_USER,
  LOGOUT
}

export default Constants;
