export const UPDATE_LOADING = "UPDATE_LOADING";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_LOGIN = "CREATE_LOGIN";
export const GET_ALL_CLINICS = "GET_ALL_CLINICS";
export const GET_DADOS_PROFILE = "GET_DADOS_PROFILE";
const Constants = {
  UPDATE_LOADING,
  CREATE_ACCOUNT,
  CREATE_LOGIN,
  GET_ALL_CLINICS,
  GET_DADOS_PROFILE
}
export default Constants;
